#!/bin/bash

# Start the application httpd instance

# Exit on any errors
set -e

APP_CLOUDTM=${OPENSHIFT_HOMEDIR}/jbossas-7-cloudtm/cloudtm
touch /tmp/debug-publish-master-endpoint.sh

function print_help {
    echo "Usage: $0 app-name namespace uuid"
    echo "Start a running application"

    echo "$0 $@" | logger -p local0.notice -t openshift_origin_httpd_start
    exit 1
}

while getopts 'd' OPTION
do
    case $OPTION in
        d) set -x
        ;;
        ?) print_help
        ;;
    esac
done

[ $# -eq 3 ] || print_help

source "/etc/openshift/node.conf"
source ${CARTRIDGE_BASE_PATH}/abstract/info/lib/util

CART_NS=$(get_cartridge_namespace_from_path)

source ${GEAR_BASE_DIR}/$3/.env/OPENSHIFT_${CART_NS}_LOCAL_MASTER_PORT
source ${GEAR_BASE_DIR}/$3/.env/OPENSHIFT_GEAR_DNS

OPENSHIFT_CART_LOCAL_MASTER_PORT=$(get_env_var_dynamic "OPENSHIFT_${CART_NS}_LOCAL_MASTER_PORT")

if [ -d "${GEAR_BASE_DIR}/$3/haproxy-1.4" ]; then
	echo ${OPENSHIFT_GEAR_DNS}:${OPENSHIFT_CART_LOCAL_MASTER_PORT}
fi

